DROP DATABASE IF EXISTS comment;
CREATE DATABASE comment;
USE comment;

DROP TABLE IF EXISTS users;
CREATE TABLE users (
  id BIGINT AUTO_INCREMENT ,
  accessKey VARCHAR(255) NOT NULL ,
  accessSecret VARCHAR(255) NOT NULL ,
  PRIMARY KEY (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8;

DROP TABLE IF EXISTS projects;
CREATE TABLE projects (
  id BIGINT AUTO_INCREMENT ,
  name VARCHAR(255) NOT NULL ,
  deleted BOOLEAN NOT NULL DEFAULT FALSE ,
  createTime DATETIME NOT NULL ,
  PRIMARY KEY (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8;

DROP TABLE IF EXISTS comments;
CREATE TABLE comments (
  id BIGINT NOT NULL ,
  parentId BIGINT NOT NULL ,
  projectId BIGINT NOT NULL ,
  boxId BIGINT NOT NULL ,
  replyUserId BIGINT NOT NULL ,
  publishUserId BIGINT NOT NULL ,
  cotent VARCHAR(500) NOT NULL ,
  publishTime DATETIME NOT NULL ,
  agree INT NOT NULL DEFAULT 0 ,
  disagree INT NOT NULL DEFAULT 0,
  PRIMARY KEY (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8;
